name: Build Unity
description: Build Unity project on Ubuntu, macOS or Windows
inputs:
  unity-path:
    description: Path to Unity executable. UNITY_PATH env will be used if not provided
    required: false
  project-path:
    description: Path to Unity project
    required: false
    default: ${{ github.workspace }}
  build-target:
    description: Build target
    required: true
  build-path:
    description: Path to build output.
    required: false
  build-version:
    required: false
    description: Set application version.
  build-number:
    description: Set application build number.
    required: false
  build-defines:
    description: Set scripting define symbols. For example, RELEASE_VERSION;ENG_VERSION
    required: false
  android-keystore-path:
    description: The path of the android keystore file.
    required: false
  android-keystore-pass:
    description: The android keystore password.
    required: false
  android-keyalias-name:
    description: The android keyalias name.
    required: false
  android-keyalias-pass:
    description: The android keyalias password.
    required: false
  build-method:
    description: Path to build method. For example, MyEditorScript.PerformBuild. Default build method will be used if not provided
    required: true
  build-method-args:
    description: Custom arguments for build method
    required: false
  build-sub-target:
    description: Build Sub Target for Standalone
    required: false
  build-custom-platform:
    description: Name of Custom build platform
    required: true
  build-environment:
    description: Build Environment
    required: true
runs:
  using: node12
  main: src/build.js
branding:
  icon: package
  color: gray-dark
